-- Dynamic Sample Data for J&K Career Navigator
-- This data supports the full dynamic, data-driven architecture

-- Insert admin users (with bcrypt hashed passwords)
INSERT INTO admins (username, email, password_hash, role, permissions) VALUES
('admin', 'admin@jkcareernavigator.com', '$2a$10$rOe.w7.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.', 'super_admin', '["read", "write", "delete", "admin"]'),
('editor', 'editor@jkcareernavigator.com', '$2a$10$rOe.w7.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.', 'editor', '["read", "write"]'),
('content_manager', 'content@jkcareernavigator.com', '$2a$10$rOe.w7.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.', 'content_manager', '["read", "write"]');

-- Insert dynamic content blocks for flexible page management
INSERT INTO content_blocks (block_type, block_name, title, subtitle, content, metadata, display_order, page_route) VALUES
('hero', 'main_hero', 'AI-Powered Career Guidance for Jammu & Kashmir', 'Discover your ideal career path with personalized recommendations', 'Navigate your future with confidence using our comprehensive career guidance platform designed specifically for students and professionals in Jammu & Kashmir.', '{"cta_text": "Start Your Journey", "cta_link": "/quiz", "background_type": "gradient", "animation": "fade-in"}', 1, '/'),

('hero', 'careers_hero', 'Explore Career Opportunities in J&K', 'Find Your Perfect Career Match', 'Discover diverse career opportunities across various sectors in Jammu & Kashmir. From technology to healthcare, tourism to agriculture - find your ideal career path.', '{"cta_text": "Browse Careers", "cta_link": "/careers", "background_type": "image"}', 1, '/careers'),

('hero', 'colleges_hero', 'Top Colleges & Universities in J&K', 'Your Gateway to Quality Education', 'Explore leading educational institutions in Jammu & Kashmir. Find the perfect college for your academic and career goals.', '{"cta_text": "Find Colleges", "cta_link": "/colleges", "background_type": "video"}', 1, '/colleges'),

('about', 'platform_about', 'About J&K Career Navigator', 'Empowering Career Decisions with AI', 'Our platform combines artificial intelligence with local expertise to provide personalized career guidance for students and professionals in Jammu & Kashmir. We understand the unique opportunities and challenges in the region and provide tailored recommendations.', '{"features": ["AI-powered recommendations", "Local expertise", "Comprehensive database", "Real-time updates"]}', 2, '/'),

('services', 'career_services', 'Our Services', 'Comprehensive Career Guidance Solutions', 'We offer a complete suite of career guidance services designed to help you make informed decisions about your professional future.', '{"service_items": [{"title": "Career Assessment", "description": "Take our comprehensive quiz to discover your strengths and interests", "icon": "assessment"}, {"title": "College Guidance", "description": "Find the best colleges and courses for your career goals", "icon": "education"}, {"title": "Industry Insights", "description": "Get real-time information about job markets and opportunities", "icon": "insights"}, {"title": "AI Counseling", "description": "Receive personalized advice from our AI career counselor", "icon": "ai"}]}', 3, '/'),

('testimonials_intro', 'testimonials_header', 'Success Stories', 'See How We''ve Helped Others', 'Read inspiring stories from students and professionals who found their ideal career paths with our guidance.', '{"show_ratings": true, "autoplay": true}', 4, '/'),

('stats', 'platform_stats', 'Our Impact', 'Helping Thousands Find Their Path', 'Numbers that showcase our commitment to career guidance excellence in Jammu & Kashmir.', '{"stats": [{"label": "Students Guided", "value": "10,000+", "icon": "users"}, {"label": "Career Paths", "value": "500+", "icon": "paths"}, {"label": "Partner Colleges", "value": "150+", "icon": "colleges"}, {"label": "Success Rate", "value": "95%", "icon": "success"}]}', 5, '/'),

('cta', 'main_cta', 'Ready to Start Your Career Journey?', 'Take the first step towards your dream career', 'Join thousands of students who have found their perfect career path with our AI-powered guidance system.', '{"primary_cta": "Take Career Quiz", "primary_link": "/quiz", "secondary_cta": "Browse Careers", "secondary_link": "/careers", "style": "gradient"}', 6, '/');

-- Insert comprehensive career data
INSERT INTO careers (title, slug, description, detailed_description, category, subcategory, education_level, skills_required, salary_range_min, salary_range_max, location, company_types, growth_prospects, opportunities_in_jk, requirements, career_path, demand_score, featured, tags) VALUES

('Software Engineer', 'software-engineer', 'Develop innovative software solutions for the growing tech sector in J&K', 'Software Engineers design, develop, and maintain software applications, systems, and platforms. In Jammu & Kashmir, the IT sector is rapidly expanding with government initiatives supporting technology development. You''ll work on everything from mobile apps to enterprise software, contributing to digital transformation initiatives across the region.', 'Technology', 'Software Development', 'Bachelor''s Degree', '["Programming", "Problem Solving", "Teamwork", "Communication", "Analytical Thinking", "Java", "Python", "JavaScript"]', 400000, 1500000, '["Srinagar", "Jammu", "Remote"]', '["IT Companies", "Startups", "Government", "E-commerce", "Consulting"]', 'Excellent growth potential with the government''s push for digital J&K. New IT parks and incubation centers are creating numerous opportunities.', 'Growing IT sector with companies like TCS, Infosys setting up offices. Government initiatives like Digital India and startup incubation programs provide excellent opportunities.', 'Bachelor''s degree in Computer Science, IT, or related field. Strong programming skills in modern languages. Understanding of software development lifecycle.', '["Junior Developer", "Software Engineer", "Senior Developer", "Tech Lead", "Engineering Manager", "CTO"]', 9, true, '["technology", "programming", "software", "IT", "digital"]'),

('Medical Doctor', 'medical-doctor', 'Provide essential healthcare services in J&K''s expanding healthcare system', 'Medical Doctors diagnose, treat, and care for patients across various specializations. J&K has a growing healthcare infrastructure with new medical colleges and hospitals being established. The region offers opportunities in both public and private healthcare sectors, with special focus on community health and medical tourism.', 'Healthcare', 'Medicine', 'MBBS + MD/MS', '["Medical Knowledge", "Empathy", "Communication", "Problem Solving", "Leadership", "Patient Care", "Clinical Skills"]', 700000, 3000000, '["Srinagar", "Jammu", "Leh", "Anantnag", "Rajouri"]', '["Government Hospitals", "Private Hospitals", "Clinics", "Medical Colleges", "Research Institutes"]', 'Excellent prospects with government healthcare expansion, new medical colleges, and growing medical tourism sector.', 'High demand due to doctor shortage. New AIIMS, medical colleges being established. Medical tourism potential in regions like Gulmarg and Pahalgam.', 'MBBS degree followed by MD/MS specialization. Clear NEET-UG and NEET-PG examinations. State medical council registration.', '["Medical Student", "Junior Resident", "Senior Resident", "Consultant", "Department Head", "Medical Director"]', 10, true, '["healthcare", "medicine", "doctor", "medical", "patient care"]'),

('Tourism Manager', 'tourism-manager', 'Lead J&K''s booming tourism industry with strategic management skills', 'Tourism Managers oversee tourism operations, develop travel packages, and ensure excellent visitor experiences. J&K''s tourism industry is experiencing unprecedented growth with government focus on promoting the region as a premier destination. This role involves working with hotels, travel agencies, and government tourism departments.', 'Tourism & Hospitality', 'Tourism Management', 'Bachelor''s Degree', '["Management", "Customer Service", "Leadership", "Communication", "Marketing", "Cultural Knowledge", "Event Planning"]', 350000, 1200000, '["Srinagar", "Gulmarg", "Pahalgam", "Leh", "Jammu", "Sonamarg"]', '["Tourism Companies", "Hotels", "Resorts", "Government Tourism", "Travel Agencies"]', 'Exceptional growth with tourism revival, new infrastructure projects, and international recognition of J&K destinations.', 'Tourism is booming with record visitor numbers. Government investments in infrastructure, new destinations being developed, and adventure tourism growing rapidly.', 'Bachelor''s in Tourism Management, Hotel Management, or related field. Knowledge of local culture, languages, and tourism products.', '["Tourism Executive", "Assistant Manager", "Manager", "Senior Manager", "General Manager", "Regional Director"]', 8, true, '["tourism", "hospitality", "travel", "management", "customer service"]'),

('Data Scientist', 'data-scientist', 'Drive data-driven decisions in J&K''s emerging digital economy', 'Data Scientists analyze large datasets to derive insights for business and governance decisions. With J&K''s focus on digital governance, smart agriculture, and data-driven policy making, there''s growing demand for professionals who can work with government data, agricultural analytics, and business intelligence.', 'Technology', 'Data Science', 'Master''s Degree', '["Statistics", "Machine Learning", "Python", "R", "SQL", "Data Visualization", "Analytics", "Problem Solving"]', 600000, 2500000, '["Srinagar", "Jammu", "Remote"]', '["Government", "IT Companies", "Research Institutes", "Startups", "Consulting"]', 'High demand expected with digital J&K initiatives, smart city projects, and data-driven governance focus.', 'Government initiatives for digital J&K, smart agriculture projects, and governance analytics creating new opportunities.', 'Master''s in Data Science, Statistics, Computer Science, or related field. Strong background in mathematics and programming.', '["Data Analyst", "Junior Data Scientist", "Data Scientist", "Senior Data Scientist", "Lead Data Scientist", "Chief Data Officer"]', 9, true, '["data science", "analytics", "machine learning", "statistics", "technology"]'),

('Agricultural Engineer', 'agricultural-engineer', 'Modernize J&K''s agriculture with innovative technology solutions', 'Agricultural Engineers develop and implement technology solutions for farming. J&K''s agriculture sector is modernizing with focus on sustainable farming, precision agriculture, and food processing. This role involves working on irrigation systems, farm machinery, and agricultural technology.', 'Agriculture', 'Agricultural Technology', 'Bachelor''s Degree', '["Engineering", "Agricultural Technology", "Project Management", "Problem Solving", "Technical Skills", "Innovation"]', 300000, 1000000, '["Srinagar", "Jammu", "Rural Areas", "Agricultural Universities"]', '["Government", "Agricultural Companies", "NGOs", "Research Institutes", "Private Farms"]', 'Good prospects with focus on agricultural modernization, precision farming, and sustainable agriculture initiatives.', 'Government support for modern agriculture, drip irrigation projects, food processing units, and agricultural technology adoption.', 'B.Tech in Agricultural Engineering or related field. Knowledge of modern agricultural practices and technology.', '["Junior Engineer", "Agricultural Engineer", "Senior Engineer", "Project Manager", "Chief Engineer", "Technical Director"]', 7, false, '["agriculture", "engineering", "technology", "farming", "rural development"]'),

('School Teacher', 'school-teacher', 'Shape young minds and contribute to educational excellence in J&K', 'School Teachers educate and mentor students across primary, secondary, and higher secondary levels. J&K is investing heavily in education infrastructure with new schools, teacher training programs, and digital education initiatives creating opportunities for dedicated educators.', 'Education', 'Teaching', 'Bachelor''s + B.Ed', '["Subject Knowledge", "Communication", "Patience", "Classroom Management", "Empathy", "Leadership", "Innovation"]', 250000, 700000, '["Throughout J&K", "Urban Areas", "Rural Areas"]', '["Government Schools", "Private Schools", "Coaching Institutes", "Online Education"]', 'Stable career with social impact. Regular recruitment, promotion opportunities, and digital education integration.', 'High demand for quality teachers, new schools being established, digital education initiatives, and teacher training programs.', 'Bachelor''s degree in relevant subject plus B.Ed qualification. Clear Teacher Eligibility Test (TET) and state-level examinations.', '["Student Teacher", "Assistant Teacher", "Teacher", "Senior Teacher", "Vice Principal", "Principal"]', 8, false, '["education", "teaching", "student development", "academic", "learning"]'),

('Digital Marketing Specialist', 'digital-marketing-specialist', 'Drive online presence for J&K businesses in the digital age', 'Digital Marketing Specialists create and manage online marketing campaigns for businesses. With J&K''s growing digital economy and e-commerce adoption, businesses need professionals who understand digital marketing, social media, and online brand management.', 'Marketing', 'Digital Marketing', 'Bachelor''s Degree', '["Digital Marketing", "Social Media", "Content Creation", "Analytics", "SEO", "Communication", "Creativity"]', 300000, 1200000, '["Srinagar", "Jammu", "Remote"]', '["Marketing Agencies", "E-commerce", "Startups", "Corporate", "Freelance"]', 'Excellent growth with increasing digital adoption, e-commerce growth, and business digitalization.', 'Growing demand as businesses go digital, e-commerce platforms expand, and tourism sector embraces digital marketing.', 'Bachelor''s degree in Marketing, Communications, or related field. Certifications in Google Ads, Facebook Marketing, and analytics tools.', '["Marketing Assistant", "Digital Marketing Executive", "Specialist", "Manager", "Head of Marketing", "CMO"]', 8, true, '["marketing", "digital", "social media", "advertising", "online", "branding"]'),

('Civil Engineer', 'civil-engineer', 'Build J&K''s infrastructure for sustainable development', 'Civil Engineers design and oversee construction of infrastructure projects including roads, bridges, buildings, and water systems. J&K is witnessing massive infrastructure development with new highways, tunnels, bridges, and smart city projects creating numerous opportunities.', 'Engineering', 'Civil Engineering', 'Bachelor''s Degree', '["Engineering Design", "Project Management", "Technical Skills", "Problem Solving", "Leadership", "Safety Management"]', 400000, 1500000, '["Srinagar", "Jammu", "Project Sites", "Urban Areas"]', '["Government", "Construction Companies", "Consulting Firms", "Infrastructure Companies"]', 'Excellent prospects with ongoing infrastructure projects, smart city initiatives, and connectivity improvements.', 'Major infrastructure projects like Delhi-Katra expressway, various tunnels, bridges, and smart city developments creating opportunities.', 'B.Tech in Civil Engineering. Professional engineering license preferred. Knowledge of latest construction technologies and software.', '["Junior Engineer", "Engineer", "Senior Engineer", "Project Manager", "Chief Engineer", "Director"]', 9, true, '["engineering", "infrastructure", "construction", "civil", "development", "projects"]'),

('Hotel Manager', 'hotel-manager', 'Lead hospitality excellence in J&K''s premium tourism destinations', 'Hotel Managers oversee all aspects of hotel operations ensuring exceptional guest experiences. With J&K''s tourism boom and new luxury properties being developed, there''s high demand for experienced hospitality professionals who understand service excellence.', 'Tourism & Hospitality', 'Hotel Management', 'Bachelor''s Degree', '["Management", "Customer Service", "Leadership", "Communication", "Problem Solving", "Operations", "Team Building"]', 400000, 1800000, '["Srinagar", "Gulmarg", "Pahalgam", "Leh", "Jammu"]', '["Hotels", "Resorts", "Hospitality Chains", "Boutique Properties", "Government Tourism"]', 'Excellent growth with tourism revival, new hotel projects, and premium hospitality segment expansion.', 'Tourism industry booming with new luxury hotels, resorts being developed, and government focus on hospitality sector growth.', 'Bachelor''s in Hotel Management, Tourism, or related field. Experience in hospitality operations and customer service.', '["Management Trainee", "Assistant Manager", "Manager", "General Manager", "Regional Manager", "VP Operations"]', 8, true, '["hospitality", "hotel", "management", "tourism", "customer service", "operations"]');

-- Insert comprehensive college data
INSERT INTO colleges (name, slug, location, address, college_type, courses, facilities, contact_info, website, established_year, ranking, fees_range, admission_process, eligibility, placements, featured, meta_title, meta_description) VALUES

('National Institute of Technology (NIT) Srinagar', 'nit-srinagar', 'Srinagar, Kashmir', 'Hazratbal, Srinagar-190006, Jammu and Kashmir', 'Engineering', '["Computer Science Engineering", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Electronics & Communication Engineering", "Chemical Engineering", "Metallurgical & Materials Engineering"]', '["Central Library", "Computer Labs", "Research Labs", "Hostel Facilities", "Sports Complex", "Auditorium", "Medical Facility", "Wi-Fi Campus", "Cafeteria", "Guest House"]', '{"phone": "0194-2420475", "email": "registrar@nitsri.ac.in", "fax": "0194-2420475"}', 'https://www.nitsri.ac.in', 1960, 1, '{"tuition_fee_per_year": 200000, "hostel_fee_per_year": 50000, "total_approximate": 250000, "scholarship_available": true}', 'JEE Main followed by JoSAA counseling for B.Tech. GATE score for M.Tech programs.', '{"jee_main_rank": "Required for B.Tech", "12th_percentage": "75% minimum with PCM", "subjects": "Physics, Chemistry, Mathematics"}', '{"average_package": 1200000, "highest_package": 4500000, "placement_percentage": 95, "top_recruiters": ["Microsoft", "Google", "Amazon", "TCS", "Infosys", "Wipro", "Accenture"]}', true, 'NIT Srinagar - Premier Engineering Institute in Kashmir', 'National Institute of Technology Srinagar is a premier engineering institution offering world-class technical education in the heart of Kashmir valley.'),

('Government Medical College (GMC) Srinagar', 'gmc-srinagar', 'Srinagar, Kashmir', 'Karan Nagar, Srinagar-190010, Jammu and Kashmir', 'Medical', '["MBBS", "MD", "MS", "Diploma Courses", "BSc Nursing", "GNM Nursing", "Paramedical Courses"]', '["Associated Hospital", "Modern Labs", "Library", "Research Facilities", "Hostel", "Anatomy Museum", "Simulation Lab", "Digital Library"]', '{"phone": "0194-2503219", "email": "principalgmcsrinagar@gmail.com", "emergency": "0194-2503219"}', 'https://www.gmcsrinagar.edu.in', 1959, 1, '{"tuition_fee_per_year": 50000, "hostel_fee_per_year": 25000, "total_approximate": 75000, "government_quota": true}', 'NEET-UG for MBBS, NEET-PG for MD/MS courses. Merit-based selection for nursing and paramedical courses.', '{"neet_score": "Required as per state cutoff", "12th_percentage": "50% minimum with PCB", "subjects": "Physics, Chemistry, Biology mandatory"}', '{"government_job_quota": "85%", "private_practice_scope": "Excellent", "specialization_opportunities": "All major specializations available"}', true, 'GMC Srinagar - Leading Medical College in J&K', 'Government Medical College Srinagar is the premier medical institution in Kashmir, offering comprehensive medical education and healthcare services.'),

('University of Kashmir', 'university-of-kashmir', 'Srinagar, Kashmir', 'Hazratbal, Srinagar-190006, Jammu and Kashmir', 'University', '["Arts", "Science", "Commerce", "Social Sciences", "Law", "Management", "Education", "Oriental Learning", "Music & Fine Arts"]', '["Central Library", "Computer Centers", "Research Labs", "Hostels", "Sports Complex", "Cultural Centers", "Botanical Garden", "Museums"]', '{"phone": "0194-2420093", "email": "registrar@kashmiruniversity.net", "website_support": "webmaster@kashmiruniversity.net"}', 'https://www.kashmiruniversity.net', 1948, 2, '{"tuition_fee_per_year": 30000, "hostel_fee_per_year": 25000, "total_approximate": 55000, "scholarship_programs": true}', 'Merit-based admission and entrance tests for various courses. Online application through university portal.', '{"12th_percentage": "45% minimum for most courses", "entrance_tests": "Required for specific programs", "category_reservation": "As per government norms"}', '{"government_jobs": "Good opportunities in education and administration", "private_sector": "Available across sectors", "higher_studies": "Excellent preparation for competitive exams"}', true, 'University of Kashmir - Premier University in J&K', 'University of Kashmir is the oldest and largest university in Jammu and Kashmir, offering diverse academic programs and research opportunities.'),

('Islamic University of Science and Technology (IUST)', 'iust-awantipora', 'Awantipora, Kashmir', 'Awantipora, Pulwama-192122, Jammu and Kashmir', 'Technology University', '["Computer Science & Engineering", "Electronics & Communication", "Mechanical Engineering", "Civil Engineering", "Food Technology", "Management", "Applied Sciences"]', '["Modern Labs", "Digital Library", "Hostels", "Sports Facilities", "Medical Center", "Mosque", "Cafeteria", "Conference Hall"]', '{"phone": "01933-247955", "email": "info@islamicuniversity.edu.in", "admission_helpline": "01933-247966"}', 'https://www.islamicuniversity.edu.in', 2005, 3, '{"tuition_fee_per_year": 60000, "hostel_fee_per_year": 35000, "total_approximate": 95000, "merit_scholarships": true}', 'IUST Entrance Test for engineering programs. JEE Main scores also accepted. Direct admission for management courses.', '{"entrance_test": "IUST CET or JEE Main for engineering", "12th_percentage": "50% minimum", "subjects": "PCM for engineering, any stream for management"}', '{"average_package": 500000, "highest_package": 1500000, "placement_percentage": 80, "top_recruiters": ["TCS", "Wipro", "HCL", "Tech Mahindra", "Cognizant"]}', false, 'IUST Awantipora - Technology Education Excellence', 'Islamic University of Science and Technology offers modern technical education with state-of-the-art facilities in the Kashmir valley.'),

('Jammu University', 'jammu-university', 'Jammu', 'Baba Saheb Ambedkar Road, Jammu-180006, Jammu and Kashmir', 'University', '["Arts", "Sciences", "Commerce", "Management", "Law", "Education", "Engineering", "Medicine", "Pharmacy"]', '{"main_facilities": ["Central Library", "Computer Labs", "Research Centers", "Hostels", "Sports Complex", "Auditoriums"], "specialized": ["Business Incubation Center", "Innovation Hub", "Cultural Center"]}', '{"phone": "0191-2456531", "email": "registrar@jammuuniversity.ac.in", "admission_cell": "0191-2456789"}', 'https://www.jammuuniversity.ac.in', 1969, 2, '{"tuition_fee_per_year": 35000, "hostel_fee_per_year": 30000, "total_approximate": 65000, "scholarship_available": true}', 'Merit-based admission and entrance tests. Online application system with counseling rounds.', '{"12th_percentage": "50% minimum for most courses", "entrance_requirements": "Subject to course requirements", "reservation_policy": "As per state government guidelines"}', '{"government_sector": "Strong placement in education and administration", "private_opportunities": "Good scope in various industries", "entrepreneurship_support": "Business incubation facilities available"}', true, 'University of Jammu - Leading Educational Institution', 'University of Jammu is a premier educational institution offering diverse academic programs and research opportunities in the Jammu region.');

-- Insert comprehensive quiz questions for better assessment
INSERT INTO quiz_questions (question, question_type, options, category, subcategory, difficulty_level, order_index, explanation) VALUES
('What type of work environment energizes you the most?', 'multiple_choice', '["Fast-paced office with collaborative teams", "Quiet laboratory or research setting", "Outdoor fieldwork and site visits", "Remote work with flexible schedule", "Hospital or clinical environment", "Classroom or training environment"]', 'work_environment', 'preference', 'easy', 1, 'Understanding your preferred work environment helps match you with careers that align with your personality and working style.'),

('Which subjects did you excel in during your studies?', 'multiple_choice', '["Mathematics and Physics", "Biology and Chemistry", "Literature and Languages", "History and Social Sciences", "Arts and Creative Studies", "Computer Science and Technology", "Commerce and Economics"]', 'academic_interests', 'subjects', 'easy', 2, 'Your academic strengths often indicate areas where you might find fulfilling career opportunities.'),

('What motivates you most in a potential career?', 'multiple_choice', '["High salary and financial security", "Helping others and making social impact", "Creative expression and innovation", "Leadership and team management", "Research and knowledge discovery", "Adventure and travel opportunities", "Job security and work-life balance"]', 'motivation', 'career_drivers', 'medium', 3, 'Understanding your core motivations helps identify careers that will keep you engaged and satisfied long-term.'),

('How do you prefer to solve complex problems?', 'multiple_choice', '["Systematic analysis with data and facts", "Creative brainstorming and innovative thinking", "Collaborative discussion with team members", "Hands-on experimentation and testing", "Research and studying best practices", "Intuitive decision-making based on experience"]', 'problem_solving', 'approach', 'medium', 4, 'Your problem-solving approach indicates which career environments and challenges you''ll thrive in.'),

('What level of education are you willing to pursue for your ideal career?', 'multiple_choice', '["12th grade / High school diploma", "Certificate or diploma courses (6 months - 2 years)", "Bachelor''s degree (3-4 years)", "Master''s degree (additional 2 years)", "Professional degree (MBBS, Engineering, Law)", "Doctoral degree (PhD) and research"]', 'education', 'commitment', 'easy', 5, 'Different careers require different levels of education. This helps us recommend realistic career paths.'),

('In which location would you prefer to build your career?', 'multiple_choice', '["Major cities (Srinagar, Jammu)", "Smaller towns within J&K", "Rural areas and villages", "Anywhere in India", "International locations", "Remote work from anywhere"]', 'location', 'preference', 'easy', 6, 'Location preferences help us suggest careers with opportunities in your preferred areas.'),

('Which work schedule appeals to you most?', 'multiple_choice', '["Regular 9-5 office hours", "Flexible hours with core time", "Shift work (healthcare, hospitality)", "Project-based with deadlines", "Seasonal work patterns", "On-call or emergency response"]', 'work_schedule', 'timing', 'medium', 7, 'Work schedule preferences vary by industry and role. This helps match you with suitable career options.'),

('What type of impact do you want to make through your work?', 'multiple_choice', '["Economic development and business growth", "Healthcare and wellness improvement", "Education and knowledge sharing", "Environmental conservation", "Technology innovation", "Social justice and community service", "Cultural preservation and arts"]', 'impact', 'society', 'medium', 8, 'The type of impact you want to make can guide you toward sectors and roles that align with your values.'),

('How important is work-life balance to you?', 'multiple_choice', '["Extremely important - I need clear boundaries", "Very important - some flexibility okay", "Moderately important - willing to work extra when needed", "Less important - I''m passionate about work", "Not important - I want maximum career growth"]', 'work_life_balance', 'priority', 'medium', 9, 'Work-life balance expectations vary by career and industry. This helps set realistic expectations.'),

('Which skills do you most enjoy developing?', 'multiple_choice', '["Technical and analytical skills", "Communication and interpersonal skills", "Creative and artistic abilities", "Leadership and management skills", "Physical and practical skills", "Research and academic skills"]', 'skills', 'development', 'medium', 10, 'Identifying skills you enjoy developing helps predict careers where you''ll continue growing and stay engaged.');

-- Insert enhanced testimonials with verification
INSERT INTO testimonials (name, email, role, company, college, testimonial, detailed_testimonial, rating, category, location, verification_status, featured) VALUES
('Dr. Arjun Sharma', 'arjun.sharma@example.com', 'Senior Software Engineer', 'Google India', 'NIT Srinagar', 'The J&K Career Navigator completely transformed my career journey. The AI-powered recommendations were spot-on!', 'I was confused about my career path after 12th grade. The platform''s comprehensive quiz identified my strengths in technology and problem-solving. The detailed information about NIT Srinagar and software engineering career paths helped me make informed decisions. Today, I''m working at Google and couldn''t be happier with my career choice. The platform''s guidance was invaluable during my preparation for JEE and throughout my college journey.', 5, 'career_success', 'Srinagar, Kashmir', 'verified', true),

('Priya Devi', 'priya.devi@example.com', 'Medical Officer', 'GMC Srinagar', 'GMC Srinagar', 'Excellent platform for medical career guidance. Helped me understand specialization options and career prospects in J&K.', 'As someone from a non-medical family, I had many questions about pursuing medicine. The platform provided detailed information about NEET preparation, medical colleges in J&K, and various specialization options. The career counseling helped me understand the commitment required and the opportunities available in our region. I''m now serving as a Medical Officer and planning my MD specialization, all thanks to the clear guidance I received.', 5, 'career_success', 'Jammu', 'verified', true),

('Mohammad Rashid', 'rashid.m@example.com', 'Hotel Manager', 'The Lalit Grand Palace', 'Kashmir University', 'Great insights into tourism and hospitality careers. The platform showed me the potential of J&K''s tourism industry.', 'I always loved interacting with people and showcasing Kashmir''s beauty, but didn''t know how to turn it into a career. The platform''s detailed analysis of the tourism industry in J&K and the various career paths available opened my eyes. From hotel management to tour operations, I learned about all opportunities. Today, I manage operations at a luxury hotel and see the industry growing exactly as the platform predicted.', 4, 'career_success', 'Srinagar, Kashmir', 'verified', true),

('Sunita Kumari', 'sunita.kumari@example.com', 'Agricultural Extension Officer', 'Department of Agriculture J&K', 'SKUAST Kashmir', 'Perfect guidance for agriculture careers. Showed me how technology is transforming farming in our region.', 'Coming from a farming family, I wanted to contribute to agriculture but through modern methods. The platform educated me about agricultural engineering, extension services, and how technology is revolutionizing farming in J&K. The information about SKUAST and various agriculture-related careers helped me choose agricultural extension. I now help farmers adopt modern techniques and see the direct impact of my work.', 5, 'career_success', 'Rural Kashmir', 'verified', false),

('Rohit Gupta', 'rohit.gupta@example.com', 'Civil Engineer', 'NHAI', 'NIT Srinagar', 'Comprehensive career information helped me choose civil engineering and understand the infrastructure opportunities in J&K.', 'I was torn between computer science and civil engineering. The platform''s detailed comparison of both fields, along with information about ongoing infrastructure projects in J&K, helped me make the right choice. The insights about career growth in civil engineering and the massive infrastructure development happening in our region convinced me. I''m now part of major highway projects connecting J&K with the rest of India.', 4, 'career_success', 'Jammu', 'verified', false);

-- Insert sample articles/blogs
INSERT INTO articles (title, slug, excerpt, content, category, tags, status, featured, reading_time, author_id) VALUES
('Top 10 Career Opportunities in J&K for 2024', 'top-career-opportunities-jk-2024', 'Discover the most promising career paths in Jammu & Kashmir with detailed insights into growth prospects and requirements.', 'The job market in Jammu & Kashmir is evolving rapidly with new opportunities emerging across various sectors. From technology to tourism, healthcare to agriculture, the region offers diverse career paths for ambitious professionals.

## 1. Software Engineering and IT
The IT sector in J&K is booming with government support and private investment. Major companies are setting up offices in Srinagar and Jammu, creating thousands of opportunities for software engineers, data scientists, and IT professionals.

## 2. Healthcare and Medical Services  
With new medical colleges and hospitals being established, there''s a growing demand for healthcare professionals. From doctors to nurses, medical technicians to healthcare administrators, the sector offers stable and rewarding careers.

## 3. Tourism and Hospitality
J&K''s tourism industry is experiencing unprecedented growth. Career opportunities include hotel management, tour operations, adventure tourism, and hospitality services.

## 4. Agriculture and Food Processing
Modern agriculture and food processing industries are expanding with government support for farmers and entrepreneurs. Opportunities exist in agricultural technology, organic farming, and food processing units.

## 5. Education and Training
The education sector is growing with new schools, colleges, and training institutes. Teaching, educational technology, and skill development are key areas of growth.

[Continue with detailed information about each sector...]', 'career_guidance', '["careers", "opportunities", "J&K", "employment", "growth"]', 'published', true, 8, (SELECT id FROM admins WHERE username = 'admin' LIMIT 1)),

('How to Choose the Right College in J&K', 'choose-right-college-jk', 'A comprehensive guide to selecting the best college for your career goals in Jammu & Kashmir.', 'Choosing the right college is one of the most important decisions you''ll make. This guide will help you evaluate colleges in J&K based on your career goals, interests, and circumstances.

## Factors to Consider

### 1. Academic Programs
- Course curriculum and relevance to industry
- Faculty qualifications and experience  
- Research opportunities and facilities
- Industry partnerships and collaborations

### 2. Infrastructure and Facilities
- Laboratory and library facilities
- Hostel and campus amenities
- Sports and recreational facilities
- Technology and digital resources

### 3. Placement and Career Support
- Placement records and statistics
- Industry connections and networking
- Career counseling and guidance
- Alumni network and support

### 4. Location and Accessibility
- Proximity to home and family
- Transportation connectivity
- Climate and environmental factors
- Cost of living and expenses

[Continue with detailed analysis...]', 'education', '["college", "education", "selection", "guidance", "J&K"]', 'published', true, 10, (SELECT id FROM admins WHERE username = 'content_manager' LIMIT 1));

-- Insert Gemini API sample logs (for demonstration)
INSERT INTO gemini_logs (endpoint, request_type, symbol, request_data, response_data, response_status, response_time, user_id) VALUES
('/api/gemini/btc', 'crypto_price', 'BTC', '{"symbol": "BTCUSD", "period": "1D"}', '{"price": 45000, "change": 2.5, "volume": 1500000, "timestamp": "2024-01-15T10:00:00Z"}', 200, 250, 'user_123'),
('/api/gemini/eth', 'crypto_price', 'ETH', '{"symbol": "ETHUSD", "period": "1D"}', '{"price": 3000, "change": -1.2, "volume": 2500000, "timestamp": "2024-01-15T10:00:00Z"}', 200, 180, 'user_456'),
('/api/gemini/market', 'market_data', 'MARKET', '{"type": "overview"}', '{"total_volume": 50000000, "market_cap": 2000000000, "active_currencies": 150}', 200, 320, null);

-- Insert sample analytics data
INSERT INTO analytics (event_type, event_category, event_action, event_data, page_url, device_type, browser) VALUES
('page_view', 'navigation', 'visit', '{"page": "careers", "source": "direct"}', '/careers', 'desktop', 'Chrome'),
('quiz_start', 'engagement', 'start_quiz', '{"quiz_type": "career_assessment"}', '/quiz', 'mobile', 'Safari'),
('career_view', 'content', 'view_career', '{"career_id": "software-engineer", "category": "technology"}', '/careers/software-engineer', 'tablet', 'Firefox'),
('college_search', 'search', 'filter_colleges', '{"filters": {"type": "engineering", "location": "srinagar"}}', '/colleges', 'desktop', 'Chrome'),
('contact_form', 'conversion', 'submit_form', '{"form_type": "contact", "category": "career_query"}', '/contact', 'mobile', 'Chrome');
